<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ro">

<head>
	<title></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>

<body bgcolor="#ffffff" style="background-color: #ffffff;">

<table style="background-color: #ffffff; width:100%;">
	<h1 style="font-size:14px; color:#333333; font-weight:700; margin: 0 0 20px 0;">{TITLE} <br>(Publicat: {DATE})</h1>
	<p style="font-size:12px; color:#333333; font-weight:400; margin: 0 0 10px 0;">{DESCRIPTION}</p>
	<a style="font-size:12px; color:#333333; font-weight:400; margin: 0 0 0px 0;" href="{LINK}" target="_blank">Vezi articolul</a>
</table>

</body>

</html>